import { WeatherType } from "@/lib/types";

const DailyForecastData = [
    { weather: WeatherType.RAINY, day: "Tue", minTemp: "21°", maxTemp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Wed", minTemp: "21°", maxTemp: "15°" },
    { weather: WeatherType.FOG, day: "Thu", minTemp: "21°", maxTemp: "15°" },
    { weather: WeatherType.SNOWY, day: "Fri", minTemp: "21°", maxTemp: "15°" },
    { weather: WeatherType.STORMY, day: "Sat", minTemp: "21°", maxTemp: "15°" },
    { weather: WeatherType.SUNNY, day: "Sun", minTemp: "21°", maxTemp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Mon", minTemp: "21°", maxTemp: "15°" }
]

const HourlyForecastData = [
    // Tue
    { weather: WeatherType.RAINY, day: "Tue", hour: 0, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Tue", hour: 1, temp: "15°" },
    { weather: WeatherType.FOG, day: "Tue", hour: 2, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Tue", hour: 3, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Tue", hour: 4, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Tue", hour: 5, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Tue", hour: 6, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Tue", hour: 7, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Tue", hour: 8, temp: "15°" },
    { weather: WeatherType.FOG, day: "Tue", hour: 9, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Tue", hour: 10, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Tue", hour: 11, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Tue", hour: 12, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Tue", hour: 13, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Tue", hour: 14, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Tue", hour: 15, temp: "15°" },
    { weather: WeatherType.FOG, day: "Tue", hour: 16, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Tue", hour: 17, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Tue", hour: 18, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Tue", hour: 19, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Tue", hour: 20, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Tue", hour: 21, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Tue", hour: 22, temp: "15°" },
    { weather: WeatherType.FOG, day: "Tue", hour: 23, temp: "15°" },

    // Wed
    { weather: WeatherType.RAINY, day: "Wed", hour: 0, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Wed", hour: 1, temp: "15°" },
    { weather: WeatherType.FOG, day: "Wed", hour: 2, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Wed", hour: 3, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Wed", hour: 4, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Wed", hour: 5, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Wed", hour: 6, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Wed", hour: 7, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Wed", hour: 8, temp: "15°" },
    { weather: WeatherType.FOG, day: "Wed", hour: 9, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Wed", hour: 10, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Wed", hour: 11, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Wed", hour: 12, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Wed", hour: 13, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Wed", hour: 14, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Wed", hour: 15, temp: "15°" },
    { weather: WeatherType.FOG, day: "Wed", hour: 16, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Wed", hour: 17, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Wed", hour: 18, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Wed", hour: 19, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Wed", hour: 20, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Wed", hour: 21, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Wed", hour: 22, temp: "15°" },
    { weather: WeatherType.FOG, day: "Wed", hour: 23, temp: "15°" },

    // Thu
    { weather: WeatherType.RAINY, day: "Thu", hour: 0, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Thu", hour: 1, temp: "15°" },
    { weather: WeatherType.FOG, day: "Thu", hour: 2, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Thu", hour: 3, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Thu", hour: 4, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Thu", hour: 5, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Thu", hour: 6, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Thu", hour: 7, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Thu", hour: 8, temp: "15°" },
    { weather: WeatherType.FOG, day: "Thu", hour: 9, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Thu", hour: 10, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Thu", hour: 11, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Thu", hour: 12, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Thu", hour: 13, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Thu", hour: 14, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Thu", hour: 15, temp: "15°" },
    { weather: WeatherType.FOG, day: "Thu", hour: 16, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Thu", hour: 17, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Thu", hour: 18, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Thu", hour: 19, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Thu", hour: 20, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Thu", hour: 21, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Thu", hour: 22, temp: "15°" },
    { weather: WeatherType.FOG, day: "Thu", hour: 23, temp: "15°" },

    // Fri
    { weather: WeatherType.RAINY, day: "Fri", hour: 0, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Fri", hour: 1, temp: "15°" },
    { weather: WeatherType.FOG, day: "Fri", hour: 2, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Fri", hour: 3, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Fri", hour: 4, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Fri", hour: 5, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Fri", hour: 6, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Fri", hour: 7, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Fri", hour: 8, temp: "15°" },
    { weather: WeatherType.FOG, day: "Fri", hour: 9, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Fri", hour: 10, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Fri", hour: 11, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Fri", hour: 12, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Fri", hour: 13, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Fri", hour: 14, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Fri", hour: 15, temp: "15°" },
    { weather: WeatherType.FOG, day: "Fri", hour: 16, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Fri", hour: 17, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Fri", hour: 18, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Fri", hour: 19, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Fri", hour: 20, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Fri", hour: 21, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Fri", hour: 22, temp: "15°" },
    { weather: WeatherType.FOG, day: "Fri", hour: 23, temp: "15°" },

    // Sat
    { weather: WeatherType.RAINY, day: "Sat", hour: 0, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Sat", hour: 1, temp: "15°" },
    { weather: WeatherType.FOG, day: "Sat", hour: 2, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Sat", hour: 3, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Sat", hour: 4, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Sat", hour: 5, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Sat", hour: 6, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Sat", hour: 7, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Sat", hour: 8, temp: "15°" },
    { weather: WeatherType.FOG, day: "Sat", hour: 9, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Sat", hour: 10, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Sat", hour: 11, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Sat", hour: 12, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Sat", hour: 13, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Sat", hour: 14, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Sat", hour: 15, temp: "15°" },
    { weather: WeatherType.FOG, day: "Sat", hour: 16, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Sat", hour: 17, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Sat", hour: 18, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Sat", hour: 19, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Sat", hour: 20, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Sat", hour: 21, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Sat", hour: 22, temp: "15°" },
    { weather: WeatherType.FOG, day: "Sat", hour: 23, temp: "15°" },

    // Sun
    { weather: WeatherType.RAINY, day: "Sun", hour: 0, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Sun", hour: 1, temp: "15°" },
    { weather: WeatherType.FOG, day: "Sun", hour: 2, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Sun", hour: 3, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Sun", hour: 4, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Sun", hour: 5, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Sun", hour: 6, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Sun", hour: 7, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Sun", hour: 8, temp: "15°" },
    { weather: WeatherType.FOG, day: "Sun", hour: 9, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Sun", hour: 10, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Sun", hour: 11, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Sun", hour: 12, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Sun", hour: 13, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Sun", hour: 14, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Sun", hour: 15, temp: "15°" },
    { weather: WeatherType.FOG, day: "Sun", hour: 16, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Sun", hour: 17, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Sun", hour: 18, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Sun", hour: 19, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Sun", hour: 20, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Sun", hour: 21, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Sun", hour: 22, temp: "15°" },
    { weather: WeatherType.FOG, day: "Sun", hour: 23, temp: "15°" },

    // Mon
    { weather: WeatherType.RAINY, day: "Mon", hour: 0, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Mon", hour: 1, temp: "15°" },
    { weather: WeatherType.FOG, day: "Mon", hour: 2, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Mon", hour: 3, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Mon", hour: 4, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Mon", hour: 5, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Mon", hour: 6, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Mon", hour: 7, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Mon", hour: 8, temp: "15°" },
    { weather: WeatherType.FOG, day: "Mon", hour: 9, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Mon", hour: 10, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Mon", hour: 11, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Mon", hour: 12, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Mon", hour: 13, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Mon", hour: 14, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Mon", hour: 15, temp: "15°" },
    { weather: WeatherType.FOG, day: "Mon", hour: 16, temp: "15°" },
    { weather: WeatherType.SNOWY, day: "Mon", hour: 17, temp: "15°" },
    { weather: WeatherType.STORMY, day: "Mon", hour: 18, temp: "15°" },
    { weather: WeatherType.SUNNY, day: "Mon", hour: 19, temp: "15°" },
    { weather: WeatherType.DRIZZLE, day: "Mon", hour: 20, temp: "15°" },
    { weather: WeatherType.RAINY, day: "Mon", hour: 21, temp: "15°" },
    { weather: WeatherType.CLOUDY, day: "Mon", hour: 22, temp: "15°" },
    { weather: WeatherType.FOG, day: "Mon", hour: 23, temp: "15°" }
];

export { DailyForecastData, HourlyForecastData };