import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans, Bricolage_Grotesque } from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { cn } from "@/lib/utils";


const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(dmSans.variable, bricolageGrotesque.variable, 'antialiased bg-w-neutral-900 text-white')}
      >
        {children}
      </body>

    </html>
  );
}
